///
/// \file configuration.hpp
///
/// \brief wordparticles configuration file
///
/// \author Martin-Pierrat Louis (mart_p)
///
/// \version 1.0.0
///
/// \date October 13, 2015
///
/// Configuration file generated by cmake.
///

#ifndef     __ENGINE_PROJECT_HPP__
# define    __ENGINE_PROJECT_HPP__

#define ENGINE_VERSION_MAJOR   2
#define ENGINE_VERSION_MINOR   0
#define ENGINE_VERSION_PATCH   0
#define ENGINE_VERSION_EXTRA   0
#define ENGINE_VERSION         ".."
#define ENGINE_VERSION_FULL    "."

#define RESOURCES_PATH          "/home/eroween/Documents/worldparticles/Engine/resources"

#endif /* !__ENGINE_HPP__ */
