////////////////////////////////////////////////////////////////////////////////
/// \file worldparticles.hpp
/// \brief wordparticles configuration file
/// \author Martin-Pierrat Louis (mart_p)
/// \version 1.0.0
/// \date October 13, 2015
///
/// Configuration file generated by cmake.
///
////////////////////////////////////////////////////////////////////////////////

#ifndef     __WORLD_PARTICLES_HPP__
# define    __WORLD_PARTICLES_HPP__

#define WORLD_PARTICLES_VERSION_MAJOR   1
#define WORLD_PARTICLES_VERSION_MINOR   0
#define WORLD_PARTICLES_VERSION_PATCH   0
#define WORLD_PARTICLES_VERSION_EXTRA   0
#define WORLD_PARTICLES_VERSION         
#define WORLD_PARTICLES_VERSION_FULL    

#endif /* !__WORLD_PARTICLES_HPP__ */
